```{r}
library(dplyr)
library(ggplot2)

# # Load the data
# airbnb_data = read.csv("../resource/asnlib/publicdata/airbnb_data.csv",header = TRUE)
# 
# #  suppress this warning message
# suppressPackageStartupMessages(library(dplyr))
# 
# 
# # Change headers to lower case (my personal preference for all analysis)
# names(airbnb_data) = tolower(names(airbnb_data))
# 
# # Strip to non-ID fields
# removeMe = c("room_id", "survey_id", "host_id", "city")
# #myDF = airbnb_data[, -which(names(airbnb_data) %in% removeMe)]
myDF=read.csv("clean_data.csv",header = TRUE)
# Explore the data
str(myDF)
summary(myDF)

# Update room type as factor
myDF$room_type = as.factor(myDF$room_type)
```

```{r}
if (!require(tidyverse)) install.packages("tidyverse")
library(tidyverse) 

```


```{r}
## SET DUMMY VARIABLES WITH "Private room" AT BASE
myDF2<- myDF %>%
  mutate(Entire_home = ifelse(room_type=="Entire home/apt",1,0))  %>%
  mutate(Shared_room = ifelse(room_type=="Shared room",1,0))

## REMOVE 'room_type' VARIABLE
myDF2 = myDF2[,-1]

## CREATE LINEAR MODEL AND RETURN SUMMARY
model = lm(price~., data=myDF2)
summary(model)


```

```{r}

newdata = data.frame(bedrooms = 2,
                     accommodates = 4,
                     reviews = 50,
                     overall_satisfaction = 4,
                     Entire_home = 0,
                     Shared_room = 0)

predict(model, newdata, interval='prediction')
```

```{r}
plot(model, which = 1)
abline(h = 0.05, col = "red", lty = 2)

```
```{r}
## CALCULATE COOKS DISTANCE
cd = cooks.distance(model)
myDF2$cooks = cd

## EXTRACT ALL VALUES WHERE CD > 0 AND CREATE NEW DATAFRAME
print(myDF2[cd>1,])

```

```{r}
## CREATE NEW DATASET
cookDF =myDF2[cd<=1,-8]

## CREATE NEW LINEAR MODEL
model2 = lm(price~., data =cookDF)
summary(model2)
```
```{r}
if (!require(car)) install.packages("car")
library(car) 
```

## 1E. Variance Inflation Factor (VIF) Function (3 points):


```{r}
## CREATE NEW MODEL WITHOUT 'room_type'
myDF3 = myDF[,-1]

## BUILD LINEAR MODEL
model3 = lm(price~., data=myDF3)
summary(model3)

## RUN VIF
vif(model3)
```

## 1F. Linear/Log Regression (6 points):¶

```{r}

## linear-linear
modelLinLin = lm(price~ reviews, data = myDF)
summary(modelLinLin)

## linear-log
modelLinLog = lm(price~ log(reviews+1), data = myDF)
summary(modelLinLog)

## log-linear
modelLogLin = lm(log(price)~ reviews, data = myDF)
summary(modelLogLin)

## log-log
modelLogLog = lm(log(price)~ log(reviews+1), data = myDF)
summary(modelLogLog)

```

```{r}

data.frame(model = c('linear-linear', 'linear-log', 'log-linear', 'log-log'), adj.r.squared =c(summary(modelLinLin)$adj.r.squared, summary(modelLinLog)$adj.r.squared,
                                                                                               summary(modelLogLin)$adj.r.squared, summary(modelLogLog)$adj.r.squared) )

```

# 2
```{r}
# Read in the dataframe
mydm <- read.csv("direct_marketing.csv", header = TRUE)

# Change headers to lower case (my personal preference for all analysis)
names(mydm) = tolower(names(mydm))

# create columns per question parameters
mydm2 <- mydm %>%
    mutate(low = ifelse(history == "Low", 1,0)) %>%
    mutate(medium = ifelse(history == "Medium", 1,0)) %>%
    mutate(high = ifelse(history == "High", 1,0)) %>%
    mutate(lowsalary = salary * low) %>%
    mutate(mediumsalary = salary * medium) %>%
    mutate(highsalary = salary * high)

summary(mydm2)
```


## 2A Fitting a Multiple Linear Regression Model (6 points):

```{r}

dmmodel1 <- lm(amountspent ~ age + ownhome + salary + low + medium + high + lowsalary + mediumsalary + highsalary, data=mydm2)
summary(dmmodel1)
```

## 2B. Making a Prediction (6 points):

```{r}
dmnewdata_none = data.frame(age = 'Middle',
                     ownhome = 'Rent',
                     salary = 75000,
                     low = 0,
                     medium = 0,
                     high = 0,
                     lowsalary = 0,
                     mediumsalary = 0,
                     highsalary = 0)

dmnewdata_low = data.frame(age = 'Middle',
                     ownhome = 'Rent',
                     salary = 75000,
                     low = 1,
                     medium = 0,
                     high = 0,
                     lowsalary = 75000,
                     mediumsalary = 0,
                     highsalary = 0)

dmnewdata_medium = data.frame(age = 'Middle',
                     ownhome = 'Rent',
                     salary = 75000,
                     low = 0,
                     medium = 1,
                     high = 0,
                     lowsalary = 0,
                     mediumsalary = 75000,
                     highsalary = 0)

dmnewdata_high = data.frame(age = 'Middle',
                     ownhome = 'Rent',
                     salary = 75000,
                     low = 0,
                     medium = 0,
                     high = 1,
                     lowsalary = 0,
                     mediumsalary = 0,
                     highsalary = 75000 )

models = list(dmnewdata_none, dmnewdata_low, dmnewdata_medium, dmnewdata_high)

pred_list = list()

for(model_test in models){
  dmpred = predict(dmmodel1, model_test)
  pred_list = append(pred_list, round(dmpred[[1]]))
}

data.frame(model=c('None', 'low', 'medium','high'), prediction = unlist(pred_list))
```

# Q3 Titanic Survival (16 points total)


```{r}
# Load library if needed
if (!require(car)) install.packages("car")
library(car)

# Load the data
data("TitanicSurvival")

# Change headers to lower case (my personal preference for all analysis)
names(TitanicSurvival) = tolower(names(TitanicSurvival))

# Update the survived values to 1 for yes and 0 for no.  
TitanicSurvival$survived = 
  ifelse(TitanicSurvival$survived == "yes",1,0)

# Explore the data
str(TitanicSurvival)
summary(TitanicSurvival)
```

##3A. Logistic Regression on Titanic (3 points):

```{r}

Tmodel = glm(survived ~ sex, data=TitanicSurvival, family = 'binomial')
summary(Tmodel)

```

